# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='precio',
            new_name='price',
        ),
    ]
