# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20161024_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
