# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_travel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='siteurl',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
