# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_travel_siteurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='travel',
            name='image2',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='travel',
            name='image3',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
