# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_auto_20161113_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='image4',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
