# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_travel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='dias',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
