# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_travel_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='includes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
